### ISSUE TITLE
Suggestion: Add common whitelist

### ISSUE THREAD

**Issue by mooleshacat** [hollabee/deeperblacklist#3]
Hey I think it would be nice to change the project and add a commonly whitelisted whitelist...

You know, so you can add youtube, etc. to commonly whitelisted, and then users can import it

The only problem with this is when a site is wrongly added, how does the user remove all of them without having to check all the boxes and click delete?

Otherwise awesome idea :)

**Comment by hollabee** [comment]
Hey!
Thanks for your interest and comment! :)

I agree, it would be great to have a common whitelist that grants access to "commonly used" sites - however, the amount of links that should be in there is massive. Further, if we would only grant access to whitelisted sites, we would start a list of censorship, which would not be the intention of Web3.0 ;)
That's why we decided to go this route.
